##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"         # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star"
sampleQCDirectory: "<full path to sample QC directory>"    # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/qc"
sampleBigWigDirectory: "<full path to sample BigWig directory>"    # e.g. sampleBigWigDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/tracks"
sampleId: <samplify sampleId>                              # e.g sampleId: 123456

# STAR
starDirectory: "<full path to STAR reference directory>"       # e.g. STARDirectory: "/net/nwgc/vol1/references/human/grc38/genome/STAR/100bp/gencodev30/bundle"

# STAR specific files (should reside in the starDirectory defined above)
referenceGenome: "<name of reference genome file>"             # e.g. referenceGenome: "Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta"
rsemReferencePrefix: "<label used as prefix for rsem files>"   # e.g. rsemReferencePrefix: "rsem_reference"
gtfFile: "<name of GTF file (used for rnaseqqc)>"              # e.g. gtfFile: "gencode.v30.GRCh38.ERCC.genes.collapsed_only.gtf"

##########################################
### Inputs  - Pick one set  Fastqs or Analysis Only
##########################################
# Fastqs & Read Groups 
fastqs:  
  - fastq1Files: "<comma separated list of full path to the fastq1 files>"
    fastq2Files: "<comma separated list of full path to the fastq2 files (in same order as fastq1Files>"
    readGroups: "<comma separated list of read group info (in same order ast fastq1Files)>"
#e.g.
# fastqs:
#   - fastq1Files: /net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_1.fastq.gz,/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_1.fastq.gz   
#     fastq2Files: /net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_2.fastq.gz,/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_2.fastq.gz 
#     readGroups: ID:HLG2HDMXY.2.TCGTACTTGC.TGTTGTGAAG CN:UW PL:illumina PU:HLG2HDMXY.2.TCGTACTTGC.TGTTGTGAAG LB:170482 SM:TOR108097 "DT:2023-05-21T10:09:22.912" , ID:HLG2HDMXY.1.TCGTACTTGC.TGTTGTGAAG CN:UW PL:illumina PU:HLG2HDMXY.1.TCGTACTTGC.TGTTGTGAAG LB:170482 SM:TOR108097 "DT:2023-05-21T10:09:16.431"

# Analysis Only -- supply the files you need for the analysis you are running
#  analysisStarBam - "VCF" and/or "QC" and/or "BigWig"
#  analysisTranscriptomeBam -"RSEM"
#  analysisSpliceJunctionsTab - "Junctions"
analysisStarBam: "<full path to star bam file>"                        # e.g analysisStarBam: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.aligned.sortedByCoord.bam
analysisTranscriptomeBam: "<full path to transcriptome bam file>"      # e.g analysisTranscriptomeBam: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.transcriptome_hits.merged.bam
analysisSpliceJunctionsTab: "<full path to spiceJunctions.tab file>"   # e.g analysisSpliceJunctionsTab: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.SJ.out.tab

##########################################
### OPTIONAL - Only use thiese paramters if you want to override the defaults 
##########################################
# customAnalysisToRun - Limit the analysis to run to only the ones in this list
customAnalysisToRun: [<list of analysis to run>]     # e.e.g customAnalysisToRun: ["RSEM", "Junctions", "VCF", "QC", "BigWig"]

##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
