##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"         # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star"
sampleQCDirectory: "<full path to sample QC directory>"    # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/qc"
sampleBigWigDirectory: "<full path to sample BigWig directory>"    # e.g. sampleBigWigDirectory: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/tracks"
sampleId: <samplify sampleId>                              # e.g sampleId: 123456

# STAR
starDirectory: "<full path to STAR reference directory>"       # e.g. STARDirectory: "/net/nwgc/vol1/references/human/grc38/genome/STAR/100bp/gencodev30/bundle"

# STAR specific files (should reside in the starDirectory defined above)
referenceGenome: "<name of reference genome file>"             # e.g. referenceGenome: "Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta"
rsemReferencePrefix: "<label used as prefix for rsem files>"   # e.g. rsemReferencePrefix: "rsem_reference"
gtfFile: "<name of GTF file (used for rnaseqqc)>"              # e.g. gtfFile: "gencode.v30.GRCh38.ERCC.genes.collapsed_only.gtf"

##########################################
### Inputs  - Pick one set flowCellLaneLibrary or Analysis Only
##########################################
# flowCellLaneLibrary (libray, fastq, and flow cell info for Read Group Id)
# Input for running steps "FastxQC" or "STAR"
flowCellLaneLibraries:
  - library: "<library id>"
    fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq1 file>"
    flowCell: "<flow cell name>"
    lane: "<flow cell lane number>"
    runDate: "<iso formatted date the flow cell was run on the sequencer"
    platform: "<sequencing platform of the flow cell>"
  - fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq1 file>"
    flowCell: "<flow cell name>"
    lane: "<flow cell lane number>"
    runDate: "<iso formatted date the flow cell was run on the sequencer"
    platform: "<sequencing platform of the flow cell>"
        
    readGroups: "<comma separated list of read group info (in same order ast fastq1Files)>"
#e.g.
# flowCellLaneLibraries:
#  - library: "123456"
#    fastq1: "/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_1.fastq.gz"
#    fastq2: "/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_1.fastq.gz"
#    flowCell: "HLG2HDMXY"
#    lane: "1"
#    runDate: "2023-05-21"
#    platform: "Illumina"
#  - library: "123456"
#    fastq1: "/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_2.fastq.gz"
#    fastq2: "/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_2.fastq.gz"
#    flowCell: "HLG2HDMXY"
#    lane: "2"
#    runDate: "2023-05-21"
#    platform: "Illumina"


# Analysis Only -- supply the files you need for the analysis you are running
#  analysisStarBam - "VCF" and/or "QC" and/or "BigWig"
#  analysisTranscriptomeBam -"RSEM"
#  analysisSpliceJunctionsTab - "Junctions"
analysisStarBam: "<full path to star bam file>"                        # e.g analysisStarBam: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.aligned.sortedByCoord.bam
analysisTranscriptomeBam: "<full path to transcriptome bam file>"      # e.g analysisTranscriptomeBam: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.transcriptome_hits.merged.bam
analysisSpliceJunctionsTab: "<full path to spiceJunctions.tab file>"   # e.g analysisSpliceJunctionsTab: "/net/nwgc/vol1/data/processed/samples/123456/rna-star/123456.SJ.out.tab

##########################################
### OPTIONAL - Only use thiese paramters if you want to override the defaults 
##########################################
# stepsToRun - Limit the steps to runj to only the ones in this list
stepsToRun: [<list of steps to run>]	  # e.g. stepsToRun: ["FastxQC", "STAR", "Analysis"]  - default in nextflow config is ["STAR", "Analysis"]

# customAnalysisToRun - Limit the analysis to run to only the ones in this list
customAnalysisToRun: [<list of analysis to run>]     # e.e.g customAnalysisToRun: ["RSEM", "Junctions", "VCF", "QC", "BigWig"]

##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
